name: Beautiful Jekyll CI

on: [push, pull_request]

jobs:
  build:
    name: Build Jekyll
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t custom-jekyll-builder .

      - name: Build the site in the custom Docker container
        run: |
          docker run \
          -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
          -e PAGES_REPO_NWO=${{ github.repository }} \
          custom-jekyll-builder /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future"
